# Generated by Django 5.1 on 2026-06-11 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'shopping_category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('recommended', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='ItemsInCart',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'shopping_itemsincart',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=256)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
                ('cancel', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'shopping_purchase',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('purchase_detail_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.purchase')),
            ],
            options={
                'db_table': 'shopping_purchasedetail',
            },
        ),
    ]
