# Generated by Django 5.1 on 2026-06-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.CharField(choices=[('20%', '20% OFF'), ('50%', '50% OFF'), ('99%', '99% OFF')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.user')),
            ],
            options={
                'db_table': 'account_coupons',
                'unique_together': {('user', 'coupon_type')},
            },
        ),
    ]
