# Generated by Django 5.1 on 2026-06-17 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coupon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coupon',
            unique_together=set(),
        ),
    ]
